# Generated by Django 3.1.7 on 2021-03-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
