# Generated by Django 3.1.7 on 2021-03-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210322_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='product_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
