# Generated by Django 3.1.7 on 2021-03-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20210322_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllShopCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShopCartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.allproduct')),
                ('shopcart_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopcart.allshopcart')),
            ],
        ),
    ]
